### ISSUE TITLE
Реализовать финальный проект курса

### ISSUE THREAD

**Issue by GolovkoStepan** [AndreyMukhametzyanov/CoursesApp#10]
Курс может иметь финальный проект. Это отдельная модель с текстом задания, ссылками и возможностью прикрепить файлы. Он имеет определенный дедлайн на выполнение. Когда пользователь начинает проект, он должен завершить его до достижения дедлайна. При этом, в качестве ответа, он отправляет свое решение (ссылка на репозиторий или прикрепленный файл). Решение оценивает преподаватель и может принять его или отправить на доработку. Проект считается завершенным если преподаватель принял решение. 

Сперва, в рамках этой задачи нужно продумать, что нам нужно: какие модели создать, как написать логику. Написать комментарии ниже.

**Comment by AndreyMukhametzyanov** [comment]
**Описание**

**От лица преподавателя**

Если юзер является создателем курса , то на странице промо курса необхдимо отобразить кнопку на создание финального задания для учеников. При переходе по данной ссылке будет отображена новая страница с формой создания финального задания. Данная форма визуально будет аналогична форме создания курса. 
Поля: Название, Описание задания, Время на выполнение. И кнопка создать/изменить. Которая меняется в зависимости от того есть ли финальный проект или нет.

**Далее я пока не понимаю как организовать проверку заданий от каждого юзера.**  (читай ниже есть мысли )

Но если преподавателя все устраивает он должен нажать на кнопку зачтено. Данное нажатие вызовет флеш оповещение что статус зачтено для студента установлен. И поменяет значение статуса в форме финального экзамена у юзера (читай ниже.) 

**От лица юзера**

Доступ к финальному проекту получает юзер который был записан на курс.
Кнопка для перехода на страницу создания финального проекта находится в самом конце списка лекций. Как только финальный проект будет зачтен появится кнопка сдачи экзамена. 
При нажатии на кнопку финального проекта мы переходим на отдельную страницу. Вверху будет располагаться само задание от преподавателя и установленный преподавателем строк и статус (зачтено или нет). Ниже форма ввода «название» проекта и «описание/решение» в формате action text. И кнопка отправить на проверку. При нажатии по которой задание отправляется преподавателю?? и запускается таймер на дедлайн. Если таймер заканчивается финальный проект автоматически считается незавершенным — отображается флеш сообщение. Тут можно не редиректить обратно на страницу с лекциями а добавить что каждый раз при нажатии на кнопку отправить  на проверку будет вызыаться флеш алерт так как таймер вышел. Либо просто редиректить вверх на страницу с алертом. 
Преподаватель имеет право изменять сроки проекта. Если преподаватель принимает проект то при переходе на страницу финального проекта будет также отображаться  флеш сообщение и меняться статус на странице задания. Далее у юзера появляется кнопка о допуске к экзамену.

**Техническая часть**

Нужна отдельная модель final_project и CRUD на нее.
Модель имеет поля task: text, execution_time: integer , status: boolean default: false
Связи: Course has_many final_project , final_project belongs_to course, has_rich_text: task
Индекс уникальности index ["user_id", "course_id"], name: "index_final_project_on_course_id_and_user_id", unique: true

Валидации task не пустой, execution_time: не пустой, нумерик, больше или равно 1 дню. 

Для хранения финальных проектов создавать ли отдельную модель? Можно вынудить пользователя отправлять финальный проект например в архиве. Тогда можно этот архив хранить в отдельное поле у юзеров, которое необходимо будет добавить.  
Таймер на джаваскрипте аналогично таймеру при сдаче экзамена.

**Comment by GolovkoStepan** [comment]
Предлагаю делать след. образом:

Для описания финального проекта будет использоваться модель FinalProject
Она описывает само задание, содержит краткое описание, прикрепленные файлы и имеет дедлайн.

Для того, чтобы зафиксировать факт старта работы по проекту мы создаем модель UserProject. Ее наличие будет свидетельствовать о том, что пользователь нажал кнопку "Начать проект". Соответственно, она будет ссылаться на сам проект и на пользователя. 

Для описания решения пользователя будет использоваться модель Reply, которая содержит ответ пользователя в текстовом виде, а так же возможность прикрепить файлы. Она же, в свою очередь, будет ссылаться на UserProject. Имеет логическое поле, описывающее "принято или нет" данное решение преподавателем.

Таким образом нам потребуются 3 модели:

FinalProject (belongs_to :course)
UserProject(belongs_to :final_project, :user)
Reply(belongs_to :user_project)

UserProject должна иметь логическое поле, описывающее "принял или нет" преподаватель решение пользователя.
Преподаватель должен иметь возможность принять или отклонить решение пользователя, предлагаю сделать отдельными кнопками, доступными преподавателю, которые находятся над (или под, на твой вкус) решением пользователя.
