### ISSUE TITLE
Добавить прогресс пользователя по курсу

### ISSUE THREAD

**Issue by GolovkoStepan** [AndreyMukhametzyanov/CoursesApp#23]
Функционал примерно такой:

На каждой лекции будет кнопка "Завершить урок". По нажатии на эту кнопку лекция считается **завершенной**, происходит автоматический переход на следующую. На странице лекций имеется прогрессбар, который отображает прогресс пользователя по курсу (отношение пройденных лекций к общему числу лекций в процентах). Финальный проект и экзамен считаются за лекцию. Прогресс сохраняется при разлогине/сбросе куков/сноса винды и так далее.

Также, на index курсов для каждого курса нужно добавить такой же прогресс бар, если пользователь записан на курс, и надпись: вы записаны.

Сперва нужно твое мнение по тому, как реализовать данный функционал. Оставь свое мнение комментарием к этой задаче.

**Comment by AndreyMukhametzyanov** [comment]
Для реализации данного функционала потребуется:
Новое поле в модели lesson - complete типа boolean. Которое будет отвечать на вопрос завершен ли данный урок. Потребуется новый маршрут next,  который будет post. А также экшен к нему в котором будет прописана логика.  При нажатии мы меняем состояние поля complete в true и редиректимся на следующую лекцию если она существует. 

Количество пройденных лекций будем вытаскивать из бд по полю complete. 
Так как Финальный проект и экзамен считаются за лекции ,то общее количество возьмем как 
количество лекций  + UserProject (для текущего пользователя если существует если нет то добавим 0) + Examination (для текущего пользователя если существует если нет то добавим 0). 

Прогресс сохраняется при разлогине/сбросе куков/сноса винды и так далее. Поэтому должен храниться в отдельной модели UserProgress
has_many :users (user belongs_to UserProgress соответственно)
current_lesson: int будем хранить текущий айди лекции
complete_percent: int  поле для сохранения прогресса
индекс уникальности для айди лекций и айди юзера.

**Comment by GolovkoStepan** [comment]
Хорошо, теперь нужно сделать следующее:

У модели course должен быть метод `parts_count`, который вернет целое число. Это число рассчитывается так: число лекций + 1 если есть экзамен + 1 если есть финальный проект. Пример:

У курса А есть 5 лекций и экзамен. Метод вернет 6
У курса Б есть 7 лекций и проект. Метод вернет 8
У курса С есть 10 лекций, проект и экзамен. Метод вернет 12
У курса Д есть 10 лекций. Метод вернет 10

У модели user должен быть метод `progress_for(course)`, принимает в качестве аргумента курс и возвращает хеш вида:

{
  completed_lessons_ids: [1, 2, 3, ...], # айдишники лекций, которые были завершены пользователем на этом курсе
  exam_complete: true, # или false, в зависимости от того, пройден ли экзамен этого курса
  project_complete: false # или true, в зависимости от того, завершен ли проект этого курса
}
