### ISSUE TITLE
Реализовать сдачу экзамена по курсу

### ISSUE THREAD

**Issue by GolovkoStepan** [AndreyMukhametzyanov/CoursesApp#9]
Автор курса должен иметь возможность создать финальный тест для курса. Нужно продумать 2 момента:

1) Написать логику создания тестов. Те как мин нужна модель теста с вопросами и ответами. Те 3 модели: тест, вопрос, ответ. Сам тест будет ссылаться на конкретный курс и иметь несколько вопросов. Каждый вопрос имеет несколько ответов. Ответ может быть верным или нет.

2) Написать логику сдачи теста. Нужен контроллер и UI, при старте теста создается дополнительная запись (отдельная модель) с результатом (процент успешного решения теста, иначе говоря, сколько было верных ответов) 

Также, как дополнительные фичи: указать ограничение числа попыток сдачи, указать разрешенное время на сдачу теста.

Сперва нужно оценить фронт работ. Хочу увидеть твои предложения, как будем делать эту задачу. Написать комментарии ниже.

**Comment by AndreyMukhametzyanov** [comment]
В lessons show будет отдельная кнопка для владельца лекций для создания теста. Она будет вести на отдельную страницу. Тут по аналогии с ссылками будем создавать вопросы на тест  (cocoon gem) .  Для юзера который записался на лекцию и не является создателем она будет недоступна. Для них будет доступна другая кнопка "Пройти тест".  При нажатии на которую будет переход на новую страницу с сформированным экзаменом если он есть.
1. Создать модель тест. Он должен быть belongs_to lesson. has_many questions. has_many answers. accepts_nested_attributes_for questions, answers.  Поле - title: text, description: text . Валидации: оба не пустые
2. Создаем модель вопрос. belongs_to test, has_many answers. Поле - title: text . Валидации: title не пустой
4. Создадим модель ответ. belongs_to test,  belongs_to questions. Поле body: text Валидации: body не пустой
5. Создать модель с результатами ответов. belongs_to answers. Поле : correct_answer  Валидации: не пустая (слабо понимаю как это сделать )
6. Проверить все связи через консоль. Добавить роуты написать заготовки для вьюх + локализация.
7. Создаем контроллер для тестов. Экшены index, для показа всех вопросов и вывода их студенту. create update и destroy,
8. Создать UI который будет рандомно смешивать вопросы. 
9.  Указать ограничение числа попыток сдачи, указать разрешенное время на сдачу теста. Я так понимаю это JavaScript

**Comment by AndreyMukhametzyanov** [comment]
Для сдачи экза. Вытаскиваем вопросы из БД. Формируем массив хэшей [{question_id: => correct_answer},{question_id: => correct_answer}....]. Для Ответа юзера такой же будем формировать только вместо correct_answer будет user_answer. Тогда может чтобы не плодить модели добавить поле user answer  в модель answer?? Далее будем сравнивать два массива либо поэлементно либо вычитанием ответов юзера из эталонного, тем самым получим несовпадающие элементы которые мы можем посчитать и вывести результат.

**Comment by GolovkoStepan** [comment]
Ниче не понял. Окей, у нас есть такой массив [{question_id => correct_answer},{question_id => correct_answer}....]
1) У вопроса мб N правильных ответов, как тогда действуем?
2) Пользователь может проходить N экзаменов по несколько раз каждый, причем мы должны хранить каждый результат прохождения. Как будем их различать? Как мы поймем, что пользователь успешно/не успешно сдал экз? Каждый раз пересчитывать будем?

`добавить поле user answer в модель answer`
Это бы сработало, если бы пользователь у нас был всегда один. Как быть, если 1000 человек проходят 1 экз?

`Далее будем сравнивать два массива либо поэлементно либо вычитанием ответов юзера из эталонного`
ты предлагаешь всякий раз, когда нам нужна инфа о том, что пользователь сдал экзамен, пересчитывать эти массивы? А если тесты поменяются?



Учти след моменты:  Нам нужно знать:
1) Справился ли пользователь с экзаменом
2) Сколько раз он сдавал экзамен
3) За какое время он его сдал.

Эта информация должна храниться, а не рассчитываться по запросу, иначе мы с нашими рубями не вывезем вообще никакой rps

**Comment by AndreyMukhametzyanov** [comment]
У записавшихся на курс юзеров будет доступна кнопка сдачи экзамена на странице со всеми лекциями.
После нажатия на нее откроется страница с краткой информацией о экзамене времени прохождения и т.п и кнопкой начать экзамен.
Техническая часть.
•	Необходим новый маршрут /exam/start 
•	Новая вьюха
•	В контроллер exam добавить member
После нажатии на эту кнопку будет выведена форма в которой сверху будет таймер чуть ниже прогресс бар сам вопрос и варианты ответов, а также кнопка «дальше». При нажатии на кнопку дальше меняется лишь вопрос и варианты ответов. После прохождения экзамена выводится результат и время прохождения экзамена.
Техническая часть.
•	Необходима отдельная модель «examinees» связанная с вопросами, которая будет хранить в себе информацию об ответах юзера, времени прохождения экза, количество попыток, и успешно ли завершился экзамен (будем считать 80% правильных ответов - успех). Или эти поля отдать на откуп в модель юзера?
•	Для вывода будем брать вопросы из course.exam.questions , ответы будем брать из course.exam.answers. Ответы выводить чекбоксами и хранить их в модели. 
•	Далее по клику на кнопку далее должен меняться вопрос. То есть если мы будем итерироваться по каждому вопросу через each то по нажатию на кнопку необходимо переходить к итерации следующей до тех пор пока course.exam.questions.count>0. Возможно ли реализовать форму и с изменением вопроса с помощью cocoon? 
•	Экзамен будет считаться завершенным, если закончились все вопросы т.е course.exam.questions.count =0
•	Далее страница обновляется или переходит на /exam/results где отображается вся сохраненная информация: процент ответов, временя прохождения экза, количество попыток, и успешно ли завершился экзамен.
•	Для подсчета процента правильных ответов будем использовать приватный boolean метод «passed_exam?» для контроллера exam. В нем будем вытаскивать из БД эталонные вопросы с ответами формировать массив вот таких хэшей {question_id => [ответ1, ответ2, ответ3]} . Далее будем вытаскивать из БД ответы юзера формировать такой же массив хэшей и вычитать из эталонного ответы юзера. И считать процент прохождения если он >= true метод вернет. И сохранит это значение в БД.
•	Если количество попыток ограничено, то по истечению попыток при нажатии на кнопку сдать экзамен на странице с лекциями должно выдаваться флеш сообщение с ошибкой.
